id: P006860
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AT884
  title: ལེགས་བཤད་ཟླ་བའི་སྣང་བ།
  author: ''
  volumes:
    7d38321b1c58491d82b2aab72a5b9d0e:
      image_group_id: I1KG2739
      title: ''
      volume_number: 1
      total_pages: 788
