id: P006860
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:27:07.056477
source_metadata:
  id: bdr:W1AT884
  title: ལེགས་བཤད་ཟླ་བའི་སྣང་བ།
  author: ''
  volumes:
    7d38321b1c58491d82b2aab72a5b9d0e:
      image_group_id: I1KG2739
      title: ''
      volume_number: 1
      total_pages: 788
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
